#!/bin/bash

##
## ${_collada_to_urdf_exe} ${_daefile} --output_file ${_urdffile} -G -A --mesh_output_dir $(rospack find package_name) --mesh_prefix 'package://package_name/mesh/'
##

URDF_FILE=
DAE_FILE=

rospack find collada_urdf_jsk_patch
if [ $? -eq 0 ]; then
    RUN_LOG="$(rosrun collada_urdf_jsk_patch collada_to_urdf $@ 2>&1)"
    errid=$?
else
    RUN_LOG="$(rosrun collada_urdf collada_to_urdf $@ 2>&1)"
    errid=$?
fi

if [ ! $errid -eq 0 ]; then
    echo "error occurred!!"
    echo "$RUN_LOG"
    exit $errid
fi

#;; output file is: input.dae
#;; Input file is: output.urdf

OUTFILE=$(echo "$RUN_LOG" | sed -n -e '/output file/p')
INFILE=$(echo "$RUN_LOG" | sed -n -e '/Input file/p')
#echo " IN: ${INFILE}"
#echo "OUT: ${OUTFILE}"

if [ ! "${INFILE}" = "" ]; then
    DAE_FILE=$(echo "${INFILE}" | sed -z -e 's/.*;; Input file is: \([^\n]*\)\n.*/\1/')
fi

if [ ! "${OUTFILE}" = "" ]; then
    URDF_FILE=$(echo "${OUTFILE}" | sed -z -e 's/.*;; output file is: \(.*\)\n.*/\1/')
else
    URDF_FILE=$(dirname ${DAE_FILE})/$(basename ${DAE_FILE} dae)urdf
fi

echo "urdf: ${URDF_FILE}"
echo " dae: ${DAE_FILE}"

sed -i -e 's@</robot>@@g' ${URDF_FILE}
rosrun euscollada collada_sensor_parser -I ${DAE_FILE} >> ${URDF_FILE}
echo "</robot>" >> ${URDF_FILE}

